### ISSUE TITLE
<CardView> not working inside <SwipeLayout>

### ISSUE THREAD

**Issue by sushant-j** [rhanb/nativescript-swipe-layout#1]
Hi, as per suggested on [this issue](https://github.com/rkhayyat/nativescript-swipe-card/issues/1), I am trying to use this library to create a set of stacked, swipe-able cards.
While using [nativescript-cardview](https://github.com/bradmartin/nativescript-cardview) inside the `<SwipeLayout>` element, I'm getting the following error:

```
[MotoG3]: An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method run failed

TypeError: nativeView.removeView is not a function
File: "file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view/view.js, line: 494, column: 23

StackTrace: 
Frame: function:'CustomLayoutView._removeViewFromNativeVisualTree', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 494, column: 24
Frame: function:'ViewBase._tearDownUI', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 471, column: 25
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 467, column: 19
Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 689, column: 14
Frame: function:'ViewBase._tearDownUI', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 466, column: 14
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 467, column: 19
Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 689, column: 14
Frame: function:'ViewBase._tearDownUI', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 466, column: 14
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 467, column: 19
Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 689, column: 14
Frame: function:'ViewBase._tearDownUI', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 466, column: 14
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 467, column: 19
Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
Frame: function:'PageBase.eachChildView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 206, column: 40
Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 689, column: 14
Frame: function:'ViewBase._tearDownUI', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 466, column: 14
Frame: function:'ViewBase._removeViewCore', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 366, column: 18
Frame: function:'ViewBase._removeView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 357, column: 14
Frame: function:'removeEntry', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 281, column: 15
Frame: function:'Frame.changeCurrentPage', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 91, column: 17
Frame: function:'Frame.setCurrent', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 80, column: 14
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/fragment.transitions.js', line: 523, column: 53
Frame: function:'invoke', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
Frame: function:'run', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13


at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
at com.tns.Runtime.callJSMethod(Runtime.java:957)
at com.tns.Runtime.callJSMethod(Runtime.java:941)
at com.tns.Runtime.callJSMethod(Runtime.java:933)
at com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
at android.os.Handler.handleCallback(Handler.java:746)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
[MotoG3]: An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method run failed

TypeError: nativeView.removeView is not a function
File: "file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view/view.js, line: 494, column: 23

StackTrace: 
Frame: function:'CustomLayoutView._removeViewFromNativeVisualTree', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 494, column: 24
Frame: function:'ViewBase._tearDownUI', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 471, column: 25
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 467, column: 19
Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 689, column: 14
Frame: function:'ViewBase._tearDownUI', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 466, column: 14
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 467, column: 19
Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 689, column: 14
Frame: function:'ViewBase._tearDownUI', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 466, column: 14
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 467, column: 19
Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 689, column: 14
Frame: function:'ViewBase._tearDownUI', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 466, column: 14
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 467, column: 19
Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
Frame: function:'PageBase.eachChildView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 206, column: 40
Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 689, column: 14
Frame: function:'ViewBase._tearDownUI', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 466, column: 14
Frame: function:'ViewBase._removeViewCore', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 366, column: 18
Frame: function:'ViewBase._removeView', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 357, column: 14
Frame: function:'removeEntry', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 281, column: 15
Frame: function:'Frame.changeCurrentPage', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 91, column: 17
Frame: function:'Frame.setCurrent', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 80, column: 14
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/fragment.transitions.js', line: 523, column: 53
Frame: function:'invoke', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
Frame: function:'run', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13


at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
at com.tns.Runtime.callJSMethod(Runtime.java:957)
at com.tns.Runtime.callJSMethod(Runtime.java:941)
at com.tns.Runtime.callJSMethod(Runtime.java:933)
at com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
at android.os.Handler.handleCallback(Handler.java:746)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
``` 

Am I missing any setup instructions?

I have created a [Playground project](https://play.nativescript.org/?template=play-js&id=JEcoMU&v=2) which shows the issue. 

Any help much appreciated!

**Comment by sushant-j** [comment]
When I try this same thing on a local device, I get a slightly different but related error:
```
this.nativeViewProtected.addView is not a function, undefined
```

**Comment by sushant-j** [comment]
UPDATE: 
Tried running the included demo projects, but same errors as above are encountered.

**Comment by pushkardeshmukh1992** [comment]
+1

**Comment by gianni1337** [comment]
I have encountered the same issue: Embedding a CardView or even other elements inside a SwipeLayout leads to this error (only on Android). iOS is working. The stack trace looks exactly as the one posted above!

I am building the app with NativeScript and Angular (see package.json below).

The core html file looks like this:
```
<SwipeLayout>
    <Label text="Error on Android"></Label>   
</SwipeLayout>
```
The Label can be replaced by any other element and will lead to this exception.

package.json:
```
    {
	"description": "NativeScript Application",
	"license": "SEE LICENSE IN <your-license-filename>",
	"readme": "NativeScript Application",
	"repository": "<fill-your-repository-here>",
	"nativescript": {
		"id": "your.domain.MyTestApp",
		"tns-ios": {
			"version": "3.4.0"
		},
		"tns-android": {
			"version": "3.4.0"
		}
	},
	"dependencies": {
		"@angular/animations": "~4.0.0",
		"@angular/common": "~4.0.0",
		"@angular/compiler": "~4.0.0",
		"@angular/core": "~4.0.0",
		"@angular/forms": "~4.0.0",
		"@angular/http": "~4.0.0",
		"@angular/platform-browser": "~4.0.0",
		"@angular/platform-browser-dynamic": "~4.0.0",
		"@angular/router": "~4.0.0",
		"email-validator": "^1.1.1",
		"nativescript-angular": "~3.0.0",
		"nativescript-cardview": "^2.0.4",
		"nativescript-ngx-fonticon": "^4.0.0",
		"nativescript-social-share": "^1.5.0",
		"nativescript-swipe-layout": "^1.0.4",
		"nativescript-theme-core": "~1.0.4",
		"reflect-metadata": "~0.1.8",
		"rxjs": "~5.2.0",
		"tns-core-modules": "~3.0.0",
		"zone.js": "0.8.2"
	},
	"devDependencies": {
		"babel-traverse": "6.26.0",
		"babel-types": "6.26.0",
		"babylon": "6.18.0",
		"lazy": "1.0.11",
		"nativescript-dev-android-snapshot": "^0.*.*",
		"nativescript-dev-typescript": "^0.4.0",
		"typescript": "~2.2.1"
	}
}
```

**Comment by sushant-j** [comment]
Update:
Since the plugin did not work for me, I instead wrote my own logic for the swipe interactions I wanted using pan gestures. It was relatively easy, and [this article](https://www.nativescript.org/blog/building-the-nativescript-swipe-cards-plugins-an-ambassador-story) helped me a lot.

**Comment by rhanb** [comment]
Hello everyone,

Sorry for taking so much time to answer. This issue may come from the latest release of nativescript `3.4`. Will dig into that 👍

**Comment by gianni1337** [comment]
Perfect, thank you!

**Comment by rhanb** [comment]
@sushant-j , I never managed to reproduce the exact same issue as you but I got an other error which was coming from the latest update of {N}. Please try the latest version of the package and let me know if you still have this issue.
